services:
  # --- Backend: FastAPI ---
  - type: web
    name: annotation-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
    # NOTE: persistent disks are not available on the free plan.
    # The disk block was removed so this service can be created on the free tier.
    plan: free

  # --- Frontend: Vite build + static hosting ---
  - type: web
    name: annotation-frontend
    env: static
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://annotation-backend.onrender.com
      - key: VITE_API_URL
        value: /api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html